<?php

// ISO 4217 currency codes → display name + symbol
return [
    // ── Major / Global ──────────────────────────────────────────────────────
    'USD' => ['name' => 'US Dollar',                'symbol' => '$'],
    'EUR' => ['name' => 'Euro',                     'symbol' => '€'],
    'GBP' => ['name' => 'British Pound',            'symbol' => '£'],
    'JPY' => ['name' => 'Japanese Yen',             'symbol' => '¥'],
    'CHF' => ['name' => 'Swiss Franc',              'symbol' => 'CHF'],
    'CAD' => ['name' => 'Canadian Dollar',          'symbol' => 'CA$'],
    'AUD' => ['name' => 'Australian Dollar',        'symbol' => 'A$'],
    'NZD' => ['name' => 'New Zealand Dollar',       'symbol' => 'NZ$'],

    // ── Middle East & North Africa ───────────────────────────────────────────
    'AED' => ['name' => 'UAE Dirham',               'symbol' => 'AED'],
    'SAR' => ['name' => 'Saudi Riyal',              'symbol' => 'SR'],
    'QAR' => ['name' => 'Qatari Riyal',             'symbol' => 'QR'],
    'KWD' => ['name' => 'Kuwaiti Dinar',            'symbol' => 'KD'],
    'BHD' => ['name' => 'Bahraini Dinar',           'symbol' => 'BD'],
    'OMR' => ['name' => 'Omani Rial',               'symbol' => 'OMR'],
    'JOD' => ['name' => 'Jordanian Dinar',          'symbol' => 'JD'],
    'LBP' => ['name' => 'Lebanese Pound',           'symbol' => 'L.L.'],
    'EGP' => ['name' => 'Egyptian Pound',           'symbol' => 'E£'],
    'IQD' => ['name' => 'Iraqi Dinar',              'symbol' => 'IQD'],
    'IRR' => ['name' => 'Iranian Rial',             'symbol' => '﷼'],
    'SYP' => ['name' => 'Syrian Pound',             'symbol' => '£S'],
    'YER' => ['name' => 'Yemeni Rial',              'symbol' => '﷼'],
    'ILS' => ['name' => 'Israeli New Shekel',       'symbol' => '₪'],
    'MAD' => ['name' => 'Moroccan Dirham',          'symbol' => 'MAD'],
    'DZD' => ['name' => 'Algerian Dinar',           'symbol' => 'DA'],
    'TND' => ['name' => 'Tunisian Dinar',           'symbol' => 'DT'],
    'LYD' => ['name' => 'Libyan Dinar',             'symbol' => 'LD'],
    'SDG' => ['name' => 'Sudanese Pound',           'symbol' => 'SDG'],
    'MRU' => ['name' => 'Mauritanian Ouguiya',      'symbol' => 'UM'],

    // ── Asia ────────────────────────────────────────────────────────────────
    'CNY' => ['name' => 'Chinese Yuan',             'symbol' => '¥'],
    'HKD' => ['name' => 'Hong Kong Dollar',         'symbol' => 'HK$'],
    'SGD' => ['name' => 'Singapore Dollar',         'symbol' => 'S$'],
    'TWD' => ['name' => 'New Taiwan Dollar',        'symbol' => 'NT$'],
    'KRW' => ['name' => 'South Korean Won',         'symbol' => '₩'],
    'INR' => ['name' => 'Indian Rupee',             'symbol' => '₹'],
    'PKR' => ['name' => 'Pakistani Rupee',          'symbol' => '₨'],
    'BDT' => ['name' => 'Bangladeshi Taka',         'symbol' => '৳'],
    'LKR' => ['name' => 'Sri Lankan Rupee',         'symbol' => 'Rs'],
    'NPR' => ['name' => 'Nepalese Rupee',           'symbol' => 'Rs'],
    'MYR' => ['name' => 'Malaysian Ringgit',        'symbol' => 'RM'],
    'IDR' => ['name' => 'Indonesian Rupiah',        'symbol' => 'Rp'],
    'THB' => ['name' => 'Thai Baht',                'symbol' => '฿'],
    'VND' => ['name' => 'Vietnamese Dong',          'symbol' => '₫'],
    'PHP' => ['name' => 'Philippine Peso',          'symbol' => '₱'],
    'MMK' => ['name' => 'Myanmar Kyat',             'symbol' => 'K'],
    'KHR' => ['name' => 'Cambodian Riel',           'symbol' => '៛'],
    'LAK' => ['name' => 'Lao Kip',                  'symbol' => '₭'],
    'BND' => ['name' => 'Brunei Dollar',            'symbol' => 'B$'],
    'MNT' => ['name' => 'Mongolian Tögrög',         'symbol' => '₮'],
    'MOP' => ['name' => 'Macanese Pataca',          'symbol' => 'P'],
    'AFN' => ['name' => 'Afghan Afghani',           'symbol' => '؋'],

    // ── Europe ──────────────────────────────────────────────────────────────
    'TRY' => ['name' => 'Turkish Lira',             'symbol' => '₺'],
    'RUB' => ['name' => 'Russian Ruble',            'symbol' => '₽'],
    'UAH' => ['name' => 'Ukrainian Hryvnia',        'symbol' => '₴'],
    'PLN' => ['name' => 'Polish Zloty',             'symbol' => 'zł'],
    'CZK' => ['name' => 'Czech Koruna',             'symbol' => 'Kč'],
    'HUF' => ['name' => 'Hungarian Forint',         'symbol' => 'Ft'],
    'RON' => ['name' => 'Romanian Leu',             'symbol' => 'lei'],
    'BGN' => ['name' => 'Bulgarian Lev',            'symbol' => 'лв'],
    'HRK' => ['name' => 'Croatian Kuna',            'symbol' => 'kn'],
    'RSD' => ['name' => 'Serbian Dinar',            'symbol' => 'RSD'],
    'DKK' => ['name' => 'Danish Krone',             'symbol' => 'kr'],
    'SEK' => ['name' => 'Swedish Krona',            'symbol' => 'kr'],
    'NOK' => ['name' => 'Norwegian Krone',          'symbol' => 'kr'],
    'ISK' => ['name' => 'Icelandic Króna',          'symbol' => 'kr'],
    'GEL' => ['name' => 'Georgian Lari',            'symbol' => '₾'],
    'AMD' => ['name' => 'Armenian Dram',            'symbol' => '֏'],
    'AZN' => ['name' => 'Azerbaijani Manat',        'symbol' => '₼'],
    'KZT' => ['name' => 'Kazakhstani Tenge',        'symbol' => '₸'],
    'UZS' => ['name' => 'Uzbekistani Som',          'symbol' => 'UZS'],
    'TJS' => ['name' => 'Tajikistani Somoni',       'symbol' => 'SM'],
    'TMT' => ['name' => 'Turkmenistani Manat',      'symbol' => 'T'],
    'KGS' => ['name' => 'Kyrgyzstani Som',          'symbol' => 'KGS'],
    'MKD' => ['name' => 'Macedonian Denar',         'symbol' => 'ден'],
    'BAM' => ['name' => 'Bosnia-Herzegovina Mark',  'symbol' => 'KM'],
    'ALL' => ['name' => 'Albanian Lek',             'symbol' => 'L'],
    'MDL' => ['name' => 'Moldovan Leu',             'symbol' => 'MDL'],
    'BYN' => ['name' => 'Belarusian Ruble',         'symbol' => 'Br'],

    // ── Africa ──────────────────────────────────────────────────────────────
    'ZAR' => ['name' => 'South African Rand',       'symbol' => 'R'],
    'NGN' => ['name' => 'Nigerian Naira',           'symbol' => '₦'],
    'KES' => ['name' => 'Kenyan Shilling',          'symbol' => 'KSh'],
    'GHS' => ['name' => 'Ghanaian Cedi',            'symbol' => 'GH₵'],
    'TZS' => ['name' => 'Tanzanian Shilling',       'symbol' => 'TSh'],
    'UGX' => ['name' => 'Ugandan Shilling',         'symbol' => 'USh'],
    'ETB' => ['name' => 'Ethiopian Birr',           'symbol' => 'Br'],
    'RWF' => ['name' => 'Rwandan Franc',            'symbol' => 'RF'],
    'MZN' => ['name' => 'Mozambican Metical',       'symbol' => 'MT'],
    'ZMW' => ['name' => 'Zambian Kwacha',           'symbol' => 'ZK'],
    'MWK' => ['name' => 'Malawian Kwacha',          'symbol' => 'MK'],
    'BWP' => ['name' => 'Botswana Pula',            'symbol' => 'P'],
    'NAD' => ['name' => 'Namibian Dollar',          'symbol' => 'N$'],
    'SZL' => ['name' => 'Swazi Lilangeni',          'symbol' => 'L'],
    'AOA' => ['name' => 'Angolan Kwanza',           'symbol' => 'Kz'],
    'CDF' => ['name' => 'Congolese Franc',          'symbol' => 'FC'],
    'XOF' => ['name' => 'West African CFA Franc',   'symbol' => 'CFA'],
    'XAF' => ['name' => 'Central African CFA Franc', 'symbol' => 'FCFA'],
    'MGA' => ['name' => 'Malagasy Ariary',          'symbol' => 'Ar'],
    'MUR' => ['name' => 'Mauritian Rupee',          'symbol' => 'Rs'],
    'SCR' => ['name' => 'Seychellois Rupee',        'symbol' => 'Rs'],
    'KMF' => ['name' => 'Comorian Franc',           'symbol' => 'CF'],
    'DJF' => ['name' => 'Djiboutian Franc',         'symbol' => 'Fdj'],
    'ERN' => ['name' => 'Eritrean Nakfa',           'symbol' => 'Nfk'],
    'SOS' => ['name' => 'Somali Shilling',          'symbol' => 'Sh'],
    'GMD' => ['name' => 'Gambian Dalasi',           'symbol' => 'D'],
    'GNF' => ['name' => 'Guinean Franc',            'symbol' => 'FG'],
    'SLL' => ['name' => 'Sierra Leonean Leone',     'symbol' => 'Le'],
    'LRD' => ['name' => 'Liberian Dollar',          'symbol' => 'L$'],
    'CVE' => ['name' => 'Cape Verdean Escudo',      'symbol' => '$'],
    'STN' => ['name' => 'São Tomé Dobra',           'symbol' => 'Db'],
    'XPF' => ['name' => 'CFP Franc',                'symbol' => 'CFP'],

    // ── Americas ────────────────────────────────────────────────────────────
    'BRL' => ['name' => 'Brazilian Real',           'symbol' => 'R$'],
    'MXN' => ['name' => 'Mexican Peso',             'symbol' => 'MX$'],
    'COP' => ['name' => 'Colombian Peso',           'symbol' => '$'],
    'ARS' => ['name' => 'Argentine Peso',           'symbol' => '$'],
    'CLP' => ['name' => 'Chilean Peso',             'symbol' => '$'],
    'PEN' => ['name' => 'Peruvian Sol',             'symbol' => 'S/'],
    'UYU' => ['name' => 'Uruguayan Peso',           'symbol' => '$U'],
    'PYG' => ['name' => 'Paraguayan Guaraní',       'symbol' => '₲'],
    'BOB' => ['name' => 'Bolivian Boliviano',       'symbol' => 'Bs.'],
    'VES' => ['name' => 'Venezuelan Bolívar',       'symbol' => 'Bs.S'],
    'GTQ' => ['name' => 'Guatemalan Quetzal',       'symbol' => 'Q'],
    'HNL' => ['name' => 'Honduran Lempira',         'symbol' => 'L'],
    'NIO' => ['name' => 'Nicaraguan Córdoba',       'symbol' => 'C$'],
    'CRC' => ['name' => 'Costa Rican Colón',        'symbol' => '₡'],
    'PAB' => ['name' => 'Panamanian Balboa',        'symbol' => 'B/.'],
    'DOP' => ['name' => 'Dominican Peso',           'symbol' => 'RD$'],
    'HTG' => ['name' => 'Haitian Gourde',           'symbol' => 'G'],
    'JMD' => ['name' => 'Jamaican Dollar',          'symbol' => 'J$'],
    'TTD' => ['name' => 'Trinidad & Tobago Dollar', 'symbol' => 'TT$'],
    'BBD' => ['name' => 'Barbadian Dollar',         'symbol' => 'Bds$'],
    'XCD' => ['name' => 'East Caribbean Dollar',    'symbol' => 'EC$'],
    'BSD' => ['name' => 'Bahamian Dollar',          'symbol' => 'B$'],
    'KYD' => ['name' => 'Cayman Islands Dollar',    'symbol' => 'CI$'],
    'BZD' => ['name' => 'Belize Dollar',            'symbol' => 'BZ$'],
    'GYD' => ['name' => 'Guyanese Dollar',          'symbol' => 'G$'],
    'SRD' => ['name' => 'Surinamese Dollar',        'symbol' => 'Sr$'],
    'CUP' => ['name' => 'Cuban Peso',               'symbol' => '$MN'],

    // ── Oceania ─────────────────────────────────────────────────────────────
    'FJD' => ['name' => 'Fijian Dollar',            'symbol' => 'FJ$'],
    'PGK' => ['name' => 'Papua New Guinean Kina',   'symbol' => 'K'],
    'SBD' => ['name' => 'Solomon Islands Dollar',   'symbol' => 'SI$'],
    'VUV' => ['name' => 'Vanuatu Vatu',             'symbol' => 'Vt'],
    'WST' => ['name' => 'Samoan Tala',              'symbol' => 'WS$'],
    'TOP' => ['name' => 'Tongan Paʻanga',           'symbol' => 'T$'],
];
